### ISSUE TITLE
bazelisk.py: "last_rc" version does not work

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazelisk#124]
```
Traceback (most recent call last):
--
  | File "/usr/bin/bazel", line 350, in <module>
  | sys.exit(main())
  | File "/usr/bin/bazel", line 346, in main
  | return execute_bazel(get_bazel_path(), argv[1:])
  | File "/usr/bin/bazel", line 339, in get_bazel_path
  | return download_bazel_into_directory(bazel_version, is_commit, bazel_directory)
  | File "/usr/bin/bazel", line 236, in download_bazel_into_directory
  | url = determine_url(version, is_commit, bazel_filename)
  | File "/usr/bin/bazel", line 228, in determine_url
  | (version, rc) = re.match(r"(\d*\.\d*(?:\.\d*)?)(rc\d+)?", version).groups()
  | AttributeError: 'NoneType' object has no attribute 'groups'

```

**Comment by philwo** [comment]
Hi @prestonvanloon,

sorry, the Python version of Bazelisk doesn't support advanced version selection like `last_rc` or `last_green`. A PR to add it would be welcome, otherwise I would recommend to use the Go version of Bazelisk if possible.

**Comment by prestonvanloon** [comment]
Thanks!
