### ISSUE TITLE
crash due to "Error while unpacking builtins_bzl"

### ISSUE THREAD

**Issue by bad-blue-bull** [bazelbuild/bazelisk#337]
bazelisk 1.12.0
bazel 5.2.0
`nr@Slackware:~/src/anki/bazel% ./bazelisk-linux-amd64 
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
FATAL: <unknown> crashed due to an internal error. Printing stack trace:
java.lang.IllegalArgumentException: Error while unpacking builtins_bzl zip resource file
        at com.google.devtools.build.lib.analysis.ConfiguredRuleClassProvider$Builder.unpackBuiltinsBzlZipResource(ConfiguredRuleClassProvider.java:501)
        at com.google.devtools.build.lib.analysis.ConfiguredRuleClassProvider$Builder.build(ConfiguredRuleClassProvider.java:522)
        at com.google.devtools.build.lib.runtime.BlazeRuntime$Builder.build(BlazeRuntime.java:1512)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1298)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:925)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:762)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:87)
Caused by: java.util.zip.ZipException: invalid entry CRC (expected 0x4ccad457 but got 0x553c3f06)
        at java.base/java.util.zip.ZipInputStream.read(Unknown Source)
        at java.base/java.io.FilterInputStream.read(Unknown Source)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)
        at com.google.devtools.build.lib.analysis.ConfiguredRuleClassProvider$Builder.unpackBuiltinsBzlZipResource(ConfiguredRuleClassProvider.java:496)
        ... 6 more`

**Comment by bad-blue-bull** [comment]
downgraded zlib from 1.2.12 to 1.2.11, now it works

**Comment by garyfeng** [comment]
trying to install bazelisk in a docker using `RUN npm install -g @bazel/bazelisk`

and running into the following error, apparently `zlib-1.2.11` is no longer there. Is this related to the above issue, and can this be fixed?

```
#28 15.96   /root/.cache/bazel/_bazel_root/cc0aafd87d0f7a193d15f74859b698bd/external/rules_proto/proto/repositories.bzl:23:21: in rules_proto_dependencies
#28 15.96 Repository rule http_archive defined at:
#28 15.96   /root/.cache/bazel/_bazel_root/cc0aafd87d0f7a193d15f74859b698bd/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
#28 15.97 WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
#28 15.97 ERROR: An error occurred during the fetch of repository 'zlib':
#28 15.97    Traceback (most recent call last):
#28 15.97       File "/root/.cache/bazel/_bazel_root/cc0aafd87d0f7a193d15f74859b698bd/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
#28 15.97               download_info = ctx.download_and_extract(
#28 15.97 Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/cc0aafd87d0f7a193d15f74859b698bd/external/zlib/temp14702099505232398883/zlib-1.2.11.tar.gz: GET returned 404 Not Found
#28 15.97 ERROR: /user/cards/model-card-toolkit/WORKSPACE:16:25: fetching http_archive rule //external:zlib: Traceback (most recent call last):
```
